export const FETCH_USERS_REQUESTS = 'FETCH_USERS_REQUESTS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const POST_NEW_POST = 'POST_NEW_POST';
